### PR TITLE
Added information when server starts

### PR DESCRIPTION
**Pull request by ummahusla**
In order not to confuse people, might be a good idea to output in a console where server is running :computer:

### CODE REVIEW

**Comment by jcampbell05** [comment]
@ummahusla The port number can actually be overridden by setting the `PORT` environmental variable, should we print that out when that is the case instead of only hardcoding it ?

**Comment by ummahusla** [comment]
@jcampbell05 Yeah, that's a more clever way of doing it.

**Comment by ummahusla** [comment]
@jcampbell05 Updated

**Comment by jcampbell05** [comment]
@ummahusla Looks great but we should still default to 3000 if `process.env.PORT` isn't set

**Comment by ummahusla** [comment]
@jcampbell05 Now it should be better 👍

**Comment by jcampbell05** [comment]
@ummahusla Merged, great first PR 👍

**Pull request merged**
