### PR TITLE
General Improvements

### PR DESCRIPTION
**Pull request by ianaya89**
- Adding ES6 syntax in main file
- Adding ES6 syntax in template file
- Adding `.env` file in template
- Checkong if `.env` file exists and create it if doesn't.

### CODE REVIEW

**Comment by jcampbell05** [comment]
Thanks 😀 would you like to be invited to our slack and added to the organisation ?

**Comment by ianaya89** [comment]
Hi, sure! Would be great. Do you need my email?

**Comment by jcampbell05** [comment]
Yes I do 😀

**Comment by ianaya89** [comment]
Ignacio.anaya89@gmail.com 
Talk you soon!

**Pull request merged**
